### PR TITLE
[test, test-pointcloud] fix eps for 32bit system

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
https://github.com/euslisp/jskeus/pull/490

### CODE REVIEW

**Comment by k-okada** [comment]
@YoheiKakiuchi why this test passwd before #490 ?

**Comment by YoheiKakiuchi** [comment]
I wonder why too.

**Comment by k-okada** [comment]
did you check with 32bit machine? it still failing... https://api.travis-ci.org/v3/job/355205966/log.txt

**Comment by YoheiKakiuchi** [comment]
@k-okada 
Sorry.
https://github.com/euslisp/jskeus/pull/497 has passed pointcloud test at 32bit system.

**Pull request merged**
