### PR TITLE
execute test with compile

### PR DESCRIPTION
**Pull request by mmurooka**
https://github.com/euslisp/jskeus/pull/492#issuecomment-369211944

### CODE REVIEW

**Comment by mmurooka** [comment]
WIP
some tests, which loads other files like https://github.com/euslisp/jskeus/blob/master/irteus/test/irteus-demo.l#L5 becomes error when compiling and testing.

**Comment by k-okada** [comment]
You can use `eval-when` to not execute when compile the source, https://github.com/euslisp/jskeus/pull/522/commits/6cf3625dfb96031fe54af70a7c13263eee2fbd6b and https://github.com/euslisp/jskeus/pull/523/files if you're ok wich tests commits, please close this PR

**Comment by k-okada** [comment]
Btw, did you have ploblem like 
https://github.com/euslisp/EusLisp/issues/324 when you try to test with compiled code?

**Comment by mmurooka** [comment]
Thank you. I close this PR.

> Btw, did you have ploblem like
euslisp/EusLisp#324 when you try to test with compiled code?

I did not notice that problem.

**Pull request closed without merging**
