### PR TITLE
add write-wrl-from-glvertices function

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**

### CODE REVIEW

**Comment by snozawa** [comment]
Is this same as `euslib/rbrain/wrl2eus.l`?
I think we need to refine these codes before just adding them to irteus.
Why did you move these code from jsk_model_tools to jskeus?

**Comment by YoheiKakiuchi** [comment]
> Is this same as euslib/rbrain/wrl2eus.l?

No. this is just converting mesh file from glvertices.

> Why did you move these code from jsk_model_tools to jskeus?

This is useful code and this is not depending on ROS.

**Comment by k-okada** [comment]
> I think we need to refine these codes before just adding them to irteus.

I think so too

**Comment by k-okada** [comment]
add reference implementation for wrl2eus and stl2eus
https://github.com/euslisp/jskeus/pull/248

**Pull request merged**
