### PR TITLE
[irteus/irtgl.l] offscreen rendering

### PR DESCRIPTION
**Pull request by furushchev**
this pull request needs https://github.com/euslisp/EusLisp/pull/186
c.f. https://github.com/jsk-ros-pkg/euslib/blob/master/demo/youhei/pfilter_test/pfilterdecls.l#L393 (private repo) and http://qiita.com/edo_m18/items/95483cabf50494f53bb5#2-3

### CODE REVIEW

**Comment by k-okada** [comment]
please add link to private repo

**Comment by furushchev** [comment]
@k-okada Added at the first comment.

**Comment by furushchev** [comment]
Now attempting to enable test code for offscreen rendering.
(Not sure if `xvfb` works or not)
CC: @k-okada

**Comment by furushchev** [comment]
Note that test code needs https://github.com/euslisp/EusLisp/pull/187

**Comment by k-okada** [comment]
please check https://github.com/jsk-ros-pkg/euslib/blob/master/jsk/jskgl.l#L1694
and https://github.com/jsk-ros-pkg/euslib/blob/346179108d5930e51e229388772e0c0e297efd47/jsk/jskc.c#L49 is an example of speed up

**Comment by k-okada** [comment]
list of c function defined in internal code
```
jsk/ckdtree.c: defun(ctx,"C-KDTREE-INIT", argv[0],C_KDTREE_INIT);
jsk/ckdtree.c: defun(ctx,"C-KDTREE-K-SEARCH", argv[0],C_KDTREE_K_SEARCH);
jsk/ckdtree.c: defun(ctx,"C-KDTREE-K-SEARCH-MATRIX", argv[0],C_KDTREE_K_SEARCH_MATRIX);
jsk/ckdtree.c: defun(ctx,"C-KDTREE-K-SEARCH-MATRIX-RAW", argv[0],C_KDTREE_K_SEARCH_MATRIX_RAW);
jsk/ckdtree.c: defun(ctx,"C-KDTREE-FR-SEARCH", argv[0],C_KDTREE_FR_SEARCH);
jsk/ckdtree.c: defun(ctx,"C-KDTREE-QUIT", argv[0], C_KDTREE_QUIT);
jsk/ckdtree.c: defun(ctx,"C-KDTREE-K-DISTANCE-POINTS", argv[0], C_KDTREE_SEARCH_AND_CALC_DISTANCE);
jsk/cregexp.c:  defun(ctx,"REG-POS",argv[0],REG_POS);
jsk/cregexp.c:  defun(ctx,"REG-MATCH-POS",argv[0],REG_MATCH_POS);
jsk/cregexp.c:  defun(ctx,"REG-MATCH",argv[0],REG_MATCH);
jsk/cregexp.c:  defun(ctx,"REG-SPLIT",argv[0],REG_SPLIT);
jsk/cregexp.c:  defun(ctx,"REG-REPLACE",argv[0],REG_REPLACE);
jsk/cregexp.c:  defun(ctx,"REG-REPLACE*",argv[0],REG_REPLACE_ALL);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-VOTE",argv[0],C_VOXEL_VOTE);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-VOTE-ARRAY",argv[0],C_VOXEL_VOTE_ARRAY);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-VOTE-INDEX",argv[0],C_VOXEL_VOTE_INDEX);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-VOTE-RAY",argv[0],C_VOXEL_VOTE_RAY);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-VOTE-HIST-ARRAY",argv[0],C_VOXEL_VOTE_HIST_ARRAY);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-STEREO-VOTE",argv[0],C_VOXEL_STEREO_VOTE);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-LABELING", argv[0], C_VOXEL_LABELING);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-HIST-VOTE", argv[0], C_HIST_VOTE);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-CALC-HLAC", argv[0], CALC_HLAC);
jsk/cvoxel.c: defun(ctx,"C-VOXEL-EXTRACT-ARRAY",argv[0],C_VOXEL_EXTRACT_ARRAY);
jsk/cvoxel.c: defun(ctx,"C-STRUCT-MATCH", argv[0], STRUCT_CALC_MATCH_HIST);
jsk/cvoxel.c: defun(ctx,"C-STRUCT-TRANSFORM", argv[0], STRUCT_TRANSFORM);
jsk/cvoxel.c: defun(ctx,"C-STRUCT-RGB2HIST", argv[0], STRUCT_RGB_HIST);
jsk/cvoxel.c: defun(ctx,"C-VOTE-DEPTH-IMAGE", argv[0], VOTE_DEPTH_IMAGE);
jsk/eusjasper.c:    defun(ctx, "JASPER-READ-IMAGE",  mod, JASPER_READ_IMAGE);
jsk/eusjasper.c:    defun(ctx, "JASPER-WRITE-IMAGE", mod, JASPER_WRITE_IMAGE);
jsk/eusrapid.c:    defun(ctx, "RAPIDMAKEMODEL", mod, RAPIDMAKEMODEL);
jsk/eusrapid.c:    defun(ctx, "RAPIDBEGINMODEL", mod, RAPIDBEGINMODEL);
jsk/eusrapid.c:    defun(ctx, "RAPIDENDMODEL", mod, RAPIDENDMODEL);
jsk/eusrapid.c:    defun(ctx, "RAPIDADDTRI", mod, RAPIDADDTRI);
jsk/eusrapid.c:    defun(ctx, "RAPIDCOLLIDE", mod, RAPIDCOLLIDE);
jsk/eusrapid.c:    defun(ctx, "RAPIDNUMCONTACTS", mod, RAPIDNUMCONTACTS);
jsk/fftlib.c:  defun(ctx,"FFT",argv[0],FFT);
jsk/fftlib.c:  defun(ctx,"INVERSE-FFT",argv[0],INVFFT);
jsk/fftlib.c:  defun(ctx,"RFFT",argv[0],RFFT);
jsk/fftlib.c:  defun(ctx,"INVERSE-RFFT",argv[0],INVRFFT);
jsk/fftlib.c:defun gplot (&rest args)
jsk/jskc.c: defun(ctx,"WRITE-FLOAT",argv[0],WRTFLT);
jsk/jskc.c: defun(ctx,"FOPEN",argv[0],FOPEN);
jsk/jskc.c: defun(ctx,"FCLOSE",argv[0],FCLOSE);
jsk/jskc.c: defun(ctx,"CTRANSPOSE-ROWS",argv[0],CTRANSPOSE_ROWS);
jsk/jskc.c: defun(ctx,"VMEAN", argv[0], VMEAN);
jsk/jskc.c: defun(ctx,"VARIANCE", argv[0], VARIANCE);
jsk/jskc.c: defun(ctx,"COVARIANCE", argv[0], COVARIANCE);
jsk/jskc.c: defun(ctx,"IOCTL",argv[0],IOCTL2);
jsk/jskc.c: defun(ctx,"FLUSHSTREAM",argv[0],FLUSHSTREAM);
jsk/jskc.c: defun(ctx,"RANGE",argv[0],RANGE);
jsk/jskc.c: defun(ctx,"MKTIME",argv[0],MKTIME);
jsk/jskc.c: defun(ctx,"SEMA-WAIT-TIMEOUT",argv[0], SEMA_WAIT_TIMEOUT);
jsk/jskgeoc.c:  defun(ctx,"C-DELAUNAY",argv[0],C_DELAUNAY);
jsk/jskgeoc.c:  defun(ctx,"C-CONVEX-HULL-3D-VERS",argv[0],C_CONVEX_HULL_3D_VERS);
jsk/jskgeoc.c:  defun(ctx,"C-DISTANCE-VERTICES-POINT",argv[0],C_DISTANCE_VERTICES_POINT);
jsk/jskgeoc.c:  defun(ctx,"C-CALC-NORMAL-FOR-POINTCLOUD",argv[0],C_CALC_NORMAL_FOR_POINTCLOUD);
jsk/jskgeoc.c:  defun(ctx,"C-PCA",argv[0],C_PCA);
jsk/jskglc.c: defun(ctx,"GLVERTEX3FV-INDEX",argv[0],GLVERTEX3FV_INDEX);
jsk/jskglc.c: defun(ctx,"GLPIXELZOOM2FV",argv[0],GLPIXELZOOM2FV);
jsk/matlib.c:  defun(ctx,"V+*",mod,VPLUS_CROSSPRODUCT); 
jsk/matlib.c:  defun(ctx,"TRANSFORM3",mod,TRANSFORM3);
jsk/matlib.c:  defun(ctx,"TRANSFORMF3",mod,TRANSFORMF3);
jsk/matlib.c:  defun(ctx,"TRANSPOSE3",mod,TRANSPOSE3);
jsk/matlib.c:  defun(ctx,"V3+",mod,VPLUS3);
jsk/matlib.c:  defun(ctx,"V3++",mod,VPLUSPLUS3);
jsk/matlib.c:  defun(ctx,"M3++",mod,MPLUSPLUS3);
jsk/matlib.c:  defun(ctx,"V3-",mod,VMINUS3);
jsk/matlib.c:  defun(ctx,"V3.",mod,VINNERPRODUCT3);
jsk/matlib.c:  defun(ctx,"V3*",mod,VCROSSPRODUCT3);
jsk/matlib.c:  defun(ctx,"SCALE3",mod,SCALEVEC3);
jsk/matlib.c:  defun(ctx,"SCALE-MATRIX3",mod,SCALE_MATRIX3);
jsk/matlib.c:  defun(ctx,"DEVIDE3",mod,DEVIDEVEC3);
jsk/matlib.c:  defun(ctx,"INCFV3",mod,INCFV3);
jsk/matlib.c:  defun(ctx,"DECFV3",mod,DECFV3);
jsk/matlib.c:  defun(ctx,"SCAFV3",mod,SCAFV3);
jsk/matlib.c:  defun(ctx,"DEVFV3",mod,DEVFV3);
jsk/matlib.c:  defun(ctx,"SCALE-INCFV3",mod,SCALE_INCFV3);
jsk/matlib.c:  defun(ctx,"SCALE-DECFV3",mod,SCALE_DECFV3);
jsk/matlib.c:  defun(ctx,"DEVIDE-V3-",mod,DEVIDE_VMINUS3);
jsk/matlib.c:  defun(ctx,"SCALE-V3-",mod,SCALE_VMINUS3);
jsk/matlib.c:  defun(ctx,"CLEAR-VEC3",mod,CLEAR_VEC3);
jsk/matlib.c:  defun(ctx,"COPY-VEC-VALUE3",mod,COPY_VEC_VALUE3);
jsk/matlib.c:  defun(ctx,"CLEAR-MAT3",mod,CLEAR_MAT3);
jsk/matlib.c:  defun(ctx,"COPY-MATRIX-VALUE3",mod,COPY_MATRIX_VALUE3);
jsk/matlib.c:  defun(ctx,"INCF-INERTIA-TENSOR",mod,INCF_INERTIA_TENSOR);
jsk/matlib.c:  defun(ctx,"MAKE-EQUATION",mod,MAKE_EQUATION);
jsk/matlib.c:  defun(ctx,"COPY-MATRIX-COLUMN-TO-FVEC3",mod,COPY_MATRIX_COLUMN_TO_FVEC3);
jsk/matlib.c:  defun(ctx,"COPY-MINUS-MATRIX-COLUMN-TO-FVEC3",
jsk/matlib.c:  defun(ctx,"COPY-MATRIX-ROW-TO-FVEC3",mod,COPY_MATRIX_ROW_TO_FVEC3);
jsk/matlib.c:  defun(ctx,"MAKE-EQUATION2",mod,MAKE_EQUATION2);
jsk/matlib.c:  defun(ctx,"INCFM3",mod,INCFM3);
jsk/matlib.c:  defun(ctx,"ROTATE-VECTOR3",mod,ROTVEC3);
jsk/matlib.c:  defun(ctx,"TRANSLATE-INERTIA",mod,TRANSLATE_INERTIA);
jsk/matlib.c:  defun(ctx,"INCF-TRANSLATE-INERTIA",mod,INCF_TRANSLATE_INERTIA);
jsk/matlib.c:  defun(ctx,"ROTATE-INERTIA",mod,ROTATE_INERTIA);
jsk/matlib.c:  defun(ctx,"WORLD-INERTIA",mod,WORLD_INERTIA);
jsk/matlib.c:  defun(ctx,"INCF-WORLD-INERTIA",mod,INCF_WORLD_INERTIA);
jsk/matlib.c:    defun(ctx,"PSEUDO-INVERSE",mod,PSEUDO_MATRIX);
jsk/matlib.c:    defun(ctx,"PSEUDO",mod,PSEUDO_MATRIX2);
jsk/matlib.c:    defun(ctx,"PSEUDO-FULL",mod,PSEUDO_MATRIX3);
jsk/matlib.c:    defun(ctx,"INV-MATRIX",mod,INVERSE_MAT);
jsk/matlib.c:    defun(ctx,"INVERSE",mod,INVERSE);
jsk/matlib.c:    defun(ctx,"LU-DS",mod,LU_DS);
jsk/matlib.c:    defun(ctx,"LU-INV",mod,LU_INV);
jsk/matlib.c:    defun(ctx,"LU-DET",mod,LU_DET);
jsk/matlib.c:    defun(ctx,"MB",mod,MB);
jsk/matlib.c:    defun(ctx,"SPRIT",mod,SPRIT);                    
jsk/matlib.c:  defun(ctx,"QL-DECOMPOSE",mod,QL_DECOMPOSE);
jsk/matlib.c:  defun(ctx,"QR-DECOMPOSE",mod,QR_DECOMPOSE);
jsk/matlib.c:  defun(ctx,"QUASI-RANDOM",mod,QUASI_RANDOM);
jsk/matlib.c:  defun(ctx,"BIT-NORM",mod,BITNORM);
jsk/posix.c: defun(ctx,"NANOSLEEP",argv[0],NANOSLEEP);
jsk/uptime.c:  defun(ctx,"UPTIME",argv[0],UPTIME);
jsk/usleep.c:  defun(ctx,"USLEEP",argv[0],USLEEP);

```

**Comment by furushchev** [comment]
please merge https://github.com/euslisp/jskeus/pull/388 first.

**Comment by k-okada** [comment]
@furushchev so do we have off screen feature on current euslisp? if not please open issue for this.

**Pull request closed without merging**
