### PR TITLE
[irteus/irtscene.l] add :(add|remove)-(object|spot) method

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
please check for compatibility ->
https://github.com/jsk-ros-pkg/euslib/blob/4276689b9f6398e7e0c6c3abd10880f5da62a978/rbrain/scene.l

--
◉ Kei Okada

**Comment by furushchev** [comment]
checked, and updated codes.
- add methods for list arguments
in https://github.com/jsk-ros-pkg/euslib/blob/4276689b9f6398e7e0c6c3abd10880f5da62a978/rbrain/scene.l#L90, I think it's better to omit optional arguments for transformation, it seems to be too complex.

**Comment by furushchev** [comment]
@k-okada How do you think about this update?

**Comment by furushchev** [comment]
Any update on this PR?

**Comment by k-okada** [comment]
merged, please add sample code when you have time.

**Comment by furushchev** [comment]
ok. I created the issue

**Pull request merged**
