### PR TITLE
fixed :convert-to-world in pointcloud 

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
This PR fixed https://github.com/euslisp/jskeus/issues/487 and
pass tests of https://github.com/euslisp/jskeus/pull/489

### CODE REVIEW

**Comment by k-okada** [comment]
what happens if we run `send pc :newcoords c` ?

**Comment by YoheiKakiuchi** [comment]
When we run ```send pc :newcoords c```, point cloud moves where origin of point cloud is newcoords
but data in the instance is not changed.

**Comment by k-okada** [comment]
it that is un-expected (or un-usuful) behavior, I thought use
`:newcoords` instead of `:move-origin-to` could be one option.
If you're sure that there is a usecase of `:newcoords` as it is, we
will introduce new method name,

C.f. if ew choose `:newcoords`, we have to think about other existing
method names, such as :move-to, ....
--
◉ Kei Okada



2018-02-27 11:39 GMT+09:00 Yohei Kakiuchi <notifications@github.com>:

**Comment by YoheiKakiuchi** [comment]
':newcoords' is called from inside of other method, such as ':transform', ':translate', ':rotate' etc.
So, if data is changed by ':newcoords', transformation of data will occur many times.
I think it is very large side effect.

Then, I intented to devide moving visual expression and transforming actual data.
Methods inherited from cas-coords do not move data, just move visual expression.
Methods in pointcloud transform data, but do not move visual expression.

**Comment by k-okada** [comment]
i see.

**Comment by k-okada** [comment]
@YoheiKakiuchi this cause error on https://api.travis-ci.org/v3/job/353633731/log.txt
it's only failing on `armhf` so 32bit issue?
you can use       `osrf/ubuntu_armhf:xenial` docker image to reproduce this error 
c.f. https://github.com/euslisp/EusLisp/blob/master/.travis.yml#L23 

```
+ irteusgl irteus/test/test-pointcloud.l
configuring by "/home/travis/jskeus/eus/lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
[31mXserver connection failed[0m;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada 
;; extending gcstack 0x2113700[16374] --> 0x2352eb8[32748] top=3c67
irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb irtgl irtglc irtviewer [34m
EusLisp 9.23(ac510d7 9ff71d9) for Linux created on 51edadd03a8f(Thu Mar 15 02:03:00 UTC 2018)[0m
TEST-NAME: test-pointcloud-create
  now testing...
[32mstart testing [test-pointcloud-create]
[0mTEST-NAME: test-pointcloud-filter
  now testing...
[32mstart testing [test-pointcloud-filter]
[0m;; filtered 17 points
;; filtered 0 points
;; filtered 21 points
;; filtered 0 points
;; filtered 24 points
;; filtered 20 points
TEST-NAME: test-pointcloud-convert
  now testing...
[32mstart testing [test-pointcloud-convert]
[0m[31m[ERROR] test (eps-v= (car (send p :point-list)) *origin-p* 9.999997e-09) failed ... ( ^[0mmstart testing [test-pointcloud-convert]
ed on 51edadd03a8f(Thu Mar 15 02:03:00 UTC 2018)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).[0m
[31m[ERROR] test (eps-v= (car (send p :point-list)) (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) 9.999997e-09) failed ... ( onvert]
ed on 51edadd03a8f(Thu Mar 15 02:03:00 UTC 2018)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
art testing [test-pointcloud-c).[0m
[31m[ERROR] test (eps-v= (car (send *point* :point-list)) (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) 9.999997e-09) failed ... ( ).^[0m
art testing [test-pointcloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00 UTC 2018)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).[0m
[31m[ERROR] test (eps-v= (car (send *point* :point-list)) pt 9.999997e-09) failed ... (  UTC 2018)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).^[0m

art testing [test-pointcloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).[0m
[31m[ERROR] test (eps-v= (send *point* :worldpos) (float-vector 0 0 0) 9.999997e-09) failed ... ( ï¿½ï¿½).^[0m

art testing [test-pointcloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).[0m
[31m[ERROR] test (eps-v= (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) *origin-p* 9.999997e-09) failed ... ( t-pointcloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
^[0m

art testing [tes).[0m
[31m[ERROR] test (eps-v= (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) *origin-p* 9.999997e-09) failed ... ( ^[0m

art testing [tes).^[0m
cloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
).[0m
[31m[ERROR] test (eps-v= (send *ccoords* :transform-vector (car (send *point* :point-list))) (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) 9.999997e-09) failed ... ( ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
).^[0m
rt testing [tes).^[0m
cloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½).[0m
[31m[ERROR] test (eps-v= (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) *origin-p* 9.999997e-09) failed ... ( m
cloud-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
ï¿½ï¿½ï¿½ï¿½).^[0m
).^[0m
rt testing [tes).^[0).[0m
[31m[ERROR] test (eps-v= (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) (float-vector 792.732 539.491 2397.94) 9.999997e-09) failed ... ( m
rt testing [tes).^[0).^[0m
-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00).^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
ï¿½ï¿½ï¿½ï¿½).^[0m
).^[0).[0m
[31m[ERROR] test (eps-v= (send (send *point* :worldcoords) :transform-vector (car (send *point* :point-list))) (float-vector 792.732 539.491 2397.94) 9.999997e-09) failed ... ( .^[0m
18)^[0mï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
ï¿½ï¿½ï¿½ï¿½).^[0m
).^[0).^[0m
sting [tes).^[0).^[0m
-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00)).[0m
[31m[ERROR] test (eps-v= (send *point* :worldpos) (send *ccoords* :pos) 9.999997e-09) failed ... ( 
-c).^[0m

ed on 51edadd03a8f(Thu Mar 15 02:03:00)).^[0m
8)^[0mï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
ï¿½ï¿½ï¿½ï¿½).^[0m
).^[0).^[0m
sting [tes).^[0).^[0m).[0m
[31m[ERROR] test (eps-v= (array-entity (send *point* :worldrot)) (array-entity (send *ccoords* :rot)) 9.999997e-09) failed ... ( f(Thu Mar 15 02:03:00)).^[0m
8)^[0mï¿½ï¿½ï¿½ï¿½ï¿½).^[0m
ï¿½ï¿½ï¿½ï¿½).^[0m
).^[0).^[0m
sting [tes).^[0).^[0m).^[0m
0m

ed on 51edadd03a8).[0m
ALL RESULTS:
  TEST-NUM: 3
    PASSED:   2
[31m    FAILURE:  1
```

**Pull request merged**
