### PR TITLE
Test HEAD version euslisp which is installed via Homebrew

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
for https://github.com/euslisp/EusLisp/issues/82#issuecomment-160513533

**Comment by wkentaro** [comment]
Is this enough? This tests by trying installing jskeus on master branch.

**Comment by k-okada** [comment]
does travis check on osx?

**Comment by wkentaro** [comment]
sorry it needs https://github.com/euslisp/jskeus/pull/302

**Pull request merged**
