### PR TITLE
[irtdyna/] describe coordinates used in :calc-zmp and :calc-static-balance-point. refer #415, #419

### PR DESCRIPTION
**Pull request by rkoyama1623**
:calc-zmp と :calc-static-balance-pointの返り値の座標系に関する記述を追加しました．

### CODE REVIEW

**Comment by k-okada** [comment]
@mmurooka please review

**Comment by mmurooka** [comment]
@rkoyama, if there is related issue, please tell me that.

```lisp
2.E1-irteusgl$ (setq *robot* (instance samplerobot-robot :init))
#<samplerobot-robot #X65673d8 SampleRobot  0.0 0.0 0.0 / 0.0 0.0 0.0>
3.E1-irteusgl$ (send *robot* :calc-zmp)
#f(12.913 -0.002859 0.0)
4.E1-irteusgl$ (send *robot* :calc-static-balance-point)
#f(12.913 -0.002859 55.35)
5.E1-irteusgl$ (send *robot* :translate (float-vector 1000 0 0) :world)
#<samplerobot-robot #X65673d8 SampleRobot  1000.0 0.0 0.0 / 0.0 0.0 0.0>
6.E1-irteusgl$ (send *robot* :calc-zmp)
#f(-3.271558e+06 -0.002859 0.0)
7.E1-irteusgl$ (send *robot* :calc-static-balance-point)
#f(1012.91 -0.002859 55.35)
```

I could understand from the above result that :calc-static-balance-point is represented in worldcoords.
For :calc-zmp, I could not understand what the following result means. If you know, could you explain?
```
6.E1-irteusgl$ (send *robot* :calc-zmp)
#f(-3.271558e+06 -0.002859 0.0)
```

**Comment by rkoyama1623** [comment]
If you execute :calc-zmp 3 times, the result will be what you want.
This is because :calc-zmp is based on dynamics of robot.
When you run 
```lisp
5.E1-irteusgl$ (send *robot* :translate (float-vector 1000 0 0) :world)
```
The robot is assumed to move forward 1000mm in 0.005 seconds(default dt in calc-zmp is 0.005sec).
https://github.com/euslisp/jskeus/blob/master/irteus/irtdyna.l#L905
This operation generate a large acceleration, and it results in the large error between the static zmp and the dynamic zmp.

**Comment by rkoyama1623** [comment]
```lisp
15.irteusgl$ (setq *robot* (instance samplerobot-robot :init))
#<samplerobot-robot #X73b13a0 SampleRobot  0.0 0.0 0.0 / 0.0 0.0 0.0>
16.irteusgl$ (send *robot* :calc-zmp)
#f(12.913 -0.002859 0.0)
17.irteusgl$ (send *robot* :calc-static-balance-point)
#f(12.913 -0.002859 55.35)
18.irteusgl$ (send *robot* :translate (float-vector 1000 0 0) :world)
#<samplerobot-robot #X73b13a0 SampleRobot  1000.0 0.0 0.0 / 0.0 0.0 0.0>
19.irteusgl$ (progn (dotimes (i 2) (send *robot* :calc-zmp)) (send *robot* :calc-zmp))
#f(1012.91 -0.002859 0.0)
20.irteusgl$ (send *robot* :calc-static-balance-point)
#f(1012.91 -0.002859 55.35)
```

**Comment by mmurooka** [comment]
I see, thank you!
LGTM.

**Comment by k-okada** [comment]
Do we need to add more comment, so that, at least experienced researcher like @mmurooka understand immediately ?

**Comment by rkoyama1623** [comment]
The difficult but comvenient point of this method may be that the result depends on historical operation such as :angle-vector, :translate, :rotate, and so on.

**Comment by mmurooka** [comment]
@rkoyama1623

Please add the following sentence to the instruction of :calc-zmp
the output depends on historical robot states of the past 3 steps. Step is incremented when this method is called.
(Please modify if necessary)

**Comment by rkoyama1623** [comment]
Sorry for late.
Updated.
@mmurooka please review.

**Comment by mmurooka** [comment]
LGTM

**Comment by rkoyama1623** [comment]
Thank you.

**Pull request merged**
