### PR TITLE
Utility function to choose good color for 10 and 20 categories and add function to convert from hex color to colormaterial

### PR DESCRIPTION
**Pull request by garaemon**
screenshot from 2015-03-19 12 02 45

Original code is d3.js [here](https://github.com/mbostock/d3/wiki/Ordinal-Scales)

Code to generate this:
```lisp
(setq *cubes* nil)
(dotimes (i 100)
  (let ((c (make-cube 100 100 100)))
    (send c :translate (float-vector (* 2 i 100) 0 0))
    (setf (get c :face-color) (color-category20 i))
    (setq *cubes* (cons c *cubes*))))
(objects *cubes*)
```

### CODE REVIEW

**Comment by k-okada** [comment]
I think https://github.com/euslisp/jskeus/blob/master/irteus/irtutil.l#L211 is the best place for function like this,

**Comment by garaemon** [comment]
Moved to irtutil.l

**Comment by k-okada** [comment]
see #179, this is what I expected, reuse hsi2rgb, but it was not as easy as I originally expected, specially https://github.com/k-okada/jskeus/commit/496a30cbf14d4b50e9a61894c1e5d671c493c465

**Comment by k-okada** [comment]
clsoed due to 179

**Pull request closed without merging**
