### PR TITLE
update :make-pqp-model for directly using glvertices

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
I updated make-pqp-model method to use glvertices directly, because converting glvertices to faces and making pqpmodel from them is very slow.

### CODE REVIEW

**Comment by snozawa** [comment]
How about glvertices-related discussion?
https://github.com/jsk-ros-pkg/jsk_model_tools/issues/41
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/125

**Comment by snozawa** [comment]
I'd like to resolve these discussions about glvertices, but how about defining these functionality in `collada-body`'s `:make-pqpmodel` method?

**Comment by YoheiKakiuchi** [comment]
I think link should have ```:pqp-model``` property. 
How to use pqpmodel in bodies from self-collision-check method ?

**Comment by snozawa** [comment]
I think we need to refine glvertices methods in general, 
but for hotfix, I'd like to find the way to define `glvertices` something in subclass.

`pqp.l` defines `make-pqpmodel` as `cascaded-coords` methods.
`glvertices` is subclass feature. 
So, it is curious to add `glvertices` something to `:make-pqpmodel` method in `pqp.l`.

**Comment by YoheiKakiuchi** [comment]
move make-pqpmodel method to glvertices

**Pull request merged**
