### PR TITLE
Support OS X on Travis

### PR DESCRIPTION
**Pull request by furushchev**
[Review on Reviewable](https://reviewable.io/reviews/euslisp/jskeus/302)

### CODE REVIEW

**Comment by wkentaro** [comment]
```
.    FAILURE:  1

    FAILURE:  1Xserver connection failedstart testing [coerse]

start testing [operator]

start testing [func]

start testing [reader]

The command "find irteus/test -iname "*.l" | grep -v unittest.l | xargs -n1 irteusgl" exited with 1.
```

**Comment by k-okada** [comment]
@furushchev if test still fails, can you rebase origin/master ?

**Comment by k-okada** [comment]
please update PR, .travsi.yml has updated, you'd better to write homebrew specific code within .travis.sh as we have in https://github.com/euslisp/EusLisp/blob/master/.travis.sh

**Comment by furushchev** [comment]
@k-okada OK. Anyway Currently one test does not pass on OSX environment. ( memory leak on gl:transparent )

**Comment by furushchev** [comment]
updated && rebased origin/master.

**Comment by k-okada** [comment]
> memory leak on gl:transparent

can you specify the test code which  could not pass on the osx?

**Comment by furushchev** [comment]
@k-okada Sorry this is work in progress. Could you revert?

**Comment by k-okada** [comment]
see https://github.com/euslisp/EusLisp/pull/178 and https://github.com/euslisp/EusLisp/pull/178 will pass all tests on osx, please confirm, or enable travis to check the test

**Comment by furushchev** [comment]
@k-okada Thank you very much! I rewrite test codes for OSX and send PR again after all PR about fix codes are merged.
(Actually in this PR I only forgot to add 1 more line...)

**Pull request merged**
