### PR TITLE
another implementation for #178

### PR DESCRIPTION
**Pull request by k-okada**
- [irtutil.l] hvs2rgv set default value for i, s
- [irtgl.l] find-color: add new rule, float-vecto [0-1], list [0-255]
- [irtutil.l] add color-category10, color-category20: Utility function to
    choose good color for 10 and 20 categories and add function to convert from
    hex color to colormaterial

### CODE REVIEW

**Comment by garaemon** [comment]
Can you show me examples of color-category10 and color-category20?
Is it enough vivid to distinguish categories?
And why hue-max is 100? it's not 360?

**Comment by k-okada** [comment]
see attached for example, if we set
```
(defun color-category20 (i)
  "Choose good color from 20 colors"
  (his2rgb (mod i 20) 1.0 0.8))
```
or
```
(defun color-category20 (i)
  "Choose good color from 20 colors"
  (his2rgb (* 18 (mod i 20)) 1.0 0.8))

```
this is just a rainbow color.

screenshot from 2015-03-20 16 31 54
screenshot from 2015-03-20 16 32 09

**Comment by garaemon** [comment]
looks good

**Comment by k-okada** [comment]
this is rainbow-color ( to catch this isseue by searching with rainbow )

**Pull request merged**
