### PR TITLE
Add closed loop robot kinematics method and add sample programs

### PR DESCRIPTION
**Pull request by snozawa**
Add closed loop robot kinematics method and add sample programs.

### CODE REVIEW

**Comment by snozawa** [comment]
2dof closed loop robot example
aa

**Comment by k-okada** [comment]
ok, so this is not a just sample program, but update robot-model with new :end-coords-list
https://github.com/snozawa/jskeus/commit/133096108d658920ae183123df6c451149fea35b

**Comment by k-okada** [comment]
basically, adding implicit rules in :init-ending is not a good idea, so `end-coords-list` seems redundant to me. In the robot-model, we assume {l/r}{arm/leg}, head, torso , so you do not have to store these information as a list, for example https://github.com/euslisp/jskeus/pull/183/files#diff-f163b6321e559c436f8b19cebde0bf9fR53 can be written without using end-coords-list

but
https://github.com/euslisp/jskeus/pull/183/files#diff-f163b6321e559c436f8b19cebde0bf9fR53, uses end-coords-list directory, In this example the robot has more end-coords than just a larm-end-coords or rarm-end-coords?

**Comment by snozawa** [comment]
First of all, sorry for confusing PR.
I was in hurry and adding end-coords-list should be separated from this PR.
Discussion was necessary.


1. Motivation to add end-coords-list
  First, here is my motivation to add end-coords-list.
  > but
  > https://github.com/euslisp/jskeus/pull/183/files#diff-f163b6321e559c436f8b19cebde0bf9fR53, uses end-coords-list directory, In this example the robot has more end-coords than just a larm-end-coords or rarm-end-coords?

  Yes, in this PR, I need to use link-list chain more than rarm, larm, .. and so on for closed loop kinematics chain.
  I also need to add more end-coords.
  Moreover, not related with closed kinematics, some users want to add optional end-coords.
  For example, default end-coords such as `larm-end-coords` is ordinaly used for grasping.
Some users want to add end-coords for palm contact to support robot's body by arms.

2. Accessor
  Next, if we are allowed to use additional end-coords based on 1, we need to discuss accessor.
  Currently there are two choise for end-coords accessor:
  2-1 Your suggestion (https://github.com/euslisp/jskeus/pull/183#commitcomment-10382523) 
  Write robot model as follows:
  ```
(defmethod aaaa-robot
  :slots (aa-end-coords)
  :super robot-model)
(defmethod aaaa-robot
  ...
  (:aa-method
     ()
     ...
     (setq aa-end-coords ec))
  (:aa-end-coords () aa-end-coords)
)
  ```
  2-2 This PR
  Add `end-coords-list` and accessor for `:end-coords` in robot-model class and write robot model as follows
  ```
(defmethod aaaa-robot
  ...
 (:aa-method
    ()
    ...
    (push ec end-coords-list)
  )
 )
  ```
  About half a year ago, we discussed accessor for `robot-model` and `cascaded-link` class features (https://github.com/jsk-ros-pkg/jsk_model_tools/issues/18).  
  In these discussions, the following accessors are allowed to use:
  a. Accessor for list
  `(send *robot* :links)`, `(send *robot* :joint-list)`, `(send *robot* :cameras)`...
  b. Accessor by given name
  `(send *robot* :link "link0")`, `(send *robot* :joint "jointA")`, `(send *robot* :camera :openni-depth)`...
  c. Accessor for limb-related features
  `(send *robot* :rarm :end-corods)`, `(send *robot* :head :cameras)`, ...
  We also add test and example codes to show valid accessors (https://github.com/euslisp/jskeus/blob/master/irteus/test/robot-model-usage.l).  
  Compared with 2-1 and 2-2, 
  -- In the discussion (https://github.com/jsk-ros-pkg/jsk_model_tools/issues/18), accessor like 2-1 is not fully discussed, not added to test codes, and not officially supported in irteus (, and I forgot accessor like 2-1 until now).So, accessor 2-1 is new implicit rule for me. 
  -- Currently, accessor 2-1 is written by manual. Accessor 2-1 is written by hand and written by model-generated-codes (https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/make-pr2-model-file.l#L109,https://github.com/euslisp/EusLisp/blob/master/models/kaz-robot.l#L2021). However, it can include bug and mistake. Actually, some robot models does not have acccessor 2-1. If we want to support accessor 2-1 officially, I'd like to add this code in `init-ending`:
   ```
        ;; this is for joint-list. we need to add this kinds of codes for links, end-coords-list, and so on.
        (eval `(defmethod ,(send (class self) :name)
              (,(send j :name) (&rest args)
               (let ((j (get self ,(send j :name))))
                 (if j (forward-message-to j args))))))
   ```
   -- By using accessor 2-2, we can use both string name and symbol name for end-coords name. However, by using accessor 2-1, we can use only symbol name and we cannot distinguish upper case and lower case.  
   So, currently I'd like to use accessor 2-2. How about this?

**Comment by k-okada** [comment]
as for 1, can we add end-coords-list to cascaded-link class?
as for 2, autogenerated is nice, but sometimes it is very hard to
understand what's going on, specially when we have trouble, it is very hard
to debug, since most of robots are automatically generate these days, so I
think generate 2-1 code seems ok for me.

--
◉ Kei Okada

**Comment by snozawa** [comment]
> as for 1, can we add end-coords-list to cascaded-link class?

Yes, end-coords is basically used for IK and IK codes are defined as `cascaded-link`.
So it is reasonable to add `end-coords-list` to `cascaded-link` class.
I created PR.
https://github.com/euslisp/jskeus/pull/185

> as for 2, autogenerated is nice, but sometimes it is very hard to

In off-line discussion, advantage of accessor 2-1 is that accessor 2-1 is faster than 2-2, because 2-2 uses `find` and 2-1 directly returns slots variables. 

Then, I have a question for accessor 2-1. 
In manually-written codes, sometimes we'd like to define and access slots variables through some kind of naming rule.
Here is example of end-coords definition.

```
(defclass aa
  :super robot-model
  :slots (end-coords-0 end-coords-1) ;; slots variables
  )
(defmethod aa
  (:init
   ()
   (prog1
       (send-super :init)
     (send self :make-ec 0)
     (send self :make-ec 1)
     ))
  (:make-ec
   (idx)
   (let ((ec (make-cascoords)))
     (push ec end-coords-list)
     (set (intern (format nil "END-COORDS-~d" idx)) ec)
     ))
  (:end-coords-0 () end-coords-0)
  (:end-coords-1 () end-coords-1)
  )
(setq *aa* (instance aa :init))
```

Then tried the following commands:
```
irteusgl$  (send *aa* :end-coords-0)
nil ;; <= end-coords-0 is expected, but nil is returned
irteusgl$ end-coords-0
#<cascaded-coords #X5624ea0  0.0 0.0 0.0 / 0.0 0.0 0.0> ;; <= end-coords-0 is set as global variable
```
In this case, `end-coords-0` is expected to be set to `aa` class slots variable.
However, `end-coords-0` is set as global variable.
How can I set slots variable in these codes?

Moreover, do we need to write codes like this for access by some kind of naming rule?
```
(dotimes (i 2)
  (send *aa* (read-from-string (format nil ":end-coords-~d" i))))
```

**Pull request merged**
